categories:
    path: /categoria
    controller: App\Controller\CategoryController::index

products:
    path: /
    controller: App\Controller\ProductController::index


product_detail:
    path: /producto/{id}
    controller: App\Controller\ProductController::detail    

category_detail:
    path: /category/{id}
    controller: App\Controller\CategoryController::detail    


producto:
    path: producto
    controller: App\Controller\ProductController::index


product_creation:
    path: /producto-nuevo
    controller: App\Controller\ProductController::creation 


category_edit:
    path: /editar-categoria/{id}
    controller: App\Controller\categoryController::edit          


product_edit:
    path: /editar-producto/{id}
    controller: App\Controller\ProductController::edit          

product_delete:
    path: /borrar/producto/{id}
    controller: App\Controller\ProductController::delete 

category_delete:
    path: /borrar/categoria/{id}
    controller: App\Controller\CategoryController::delete        

register:
    path: /registro
    controller: App\Controller\CategoryController::register

redirect:
    path: /redirection
    controller: App\Controller\HomeController::redirection
